import NavBar from "@/components/NavBar/NavBar";
import type { Metadata } from "next";
import { Montserrat } from 'next/font/google'
import "./globals.css";

const montserrat = Montserrat({subsets: ["latin"]});


export const metadata: Metadata = {
  title: "Cars App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} bg-white text-black`}>
        <NavBar/>
        {children}
      </body>
    </html>
  );
}
