// src/app/layout.tsx
import NavBar from "@/components/NavBar/NavBar";
import Footer from "@/components/Footer/Footer";
import type { Metadata } from "next";
import { Montserrat } from 'next/font/google';
import "./globals.css";
import { config } from '@fortawesome/fontawesome-svg-core';
import '@fortawesome/fontawesome-svg-core/styles.css';
import ReduxProvider from '../redux/ReduxProvider';  // Importa el nuevo componente

config.autoAddCss = false;

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Cars App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} bg-white text-black`}>
        <ReduxProvider>  
          <NavBar />
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}